version: '3.8'

services:
  db:
      image: mongo:5.0
      networks:
        - chess-app-network
      ports:
      - 27017:27017
  api:
    build: .
    networks:
      - chess-app-network
    ports:
      - 8000:8000
    depends_on:
      - db
networks:
  chess-app-network:
    driver: bridge